[project]
name = "benefits-screening-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
]


[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
